<?php
$profile = $this->planet->getProfile();
?>
<table class="planet">
    <tr>
        <td colspan="2"><img src="/img/planets/default.jpg"></td>
    </tr>
    <tr>
        <td><?= _("Diameter"); ?></td>
        <td><?= number_format( $profile->getDiameter(), 0, ",", "."); ?> <?= _("ml"); ?></td>
    </tr>
    <tr>
        <td><?= _("Fields usage"); ?></td>
        <td>0%</td>
    </tr>
    <tr>
        <td><?= _("Temperature"); ?></td>
        <td><?= _("From"); ?> <?= $profile->getMinTemperature();?><sup>o</sup> <?= _("to"); ?> <?= $profile->getMaxTemperature(); ?><sup>o</sup></td>
    </tr>
    <tr>
        <td><?= _("Coordinates"); ?></td>
        <td>[<?= $this->displayCoords( $this->planet->getCoords() ); ?>]</td>
    </tr>
    <tr>
        <td colspan="2">
            <a href="/infrastructure/<?= $this->planet->getId(); ?>"><?= _("Infrastructure"); ?></a>
        </td>
    </tr>
</table>