<ul>
    <li>
        <ul>
            <li><strong><?= _("Growing"); ?></strong></li>
            <li><a href="/"><?= _("Overview"); ?></a></li>
            <li><a href="/buildings"><?= _("Buildings"); ?></a></li>
            <li><a href="/buildings/research"><?= _("Research"); ?></a></li>
            <li><a href="/buildings/fleet"><?= _("Docs"); ?></a></li>
            <li><a href="/buildings/defence"><?= _("Defence"); ?></a></li>
            <li><a href="/fleet"><?= _("Fleet"); ?></a></li>
            <li><a href="/officier"><?= _("Officers"); ?></a></li>
        </ul>
    </li>
    <li>
        <ul>
            <li><strong><?= _("Trading:"); ?></strong></li>
            <li><a href="/trade/bl"><?= _("Black list"); ?></a></li>
            <li><a href="/services"><?= _("Services"); ?></a></li>
        </ul>
    </li>
    <li>
        <ul>
            <li><strong><?= _("Observatory:"); ?></strong></li>
            <li><a href="/galaxy"><?= _("Galaxy"); ?></a></li>
            <li><a href="/impire"><?= _("Impire"); ?></a></li>
            <li><a href="/resources"><?= _("Resources"); ?></a></li>
            <li><a href="/technologies"><?= _("Technologies"); ?></a></li>
            <li><a href="/federations"><?= _("Federations"); ?></a></li>
        </ul>
    </li>
    <li>
        <ul>
            <li><strong><?= _("Other:"); ?></strong></li>
            <li><a href="/stats"><?= _("Statistics"); ?></a></li>
            <li><a href="/records"><?= _("Records"); ?></a></li>
            <li><a href="/search"><?= _("Search"); ?></a></li>
            <li><a href="/banned"><?= _("Blacklist"); ?></a></li>
        </ul>
    </li>
    <li>
        <ul>
            <li><strong><?= _("Communications"); ?></strong></li>
            <li><a href="/my/messages"><?= _("Messages"); ?></a></li>
            <li><a href="/forum"><?= _("Forum"); ?></a></li>
            <li><a href="/support/bug"><?= _("Send bug report"); ?></a></li>
            <li><a href="/my/friends"><?= _("Friends"); ?></a></li>
            <li><a href="/my/notes"><?= _("Notes"); ?></a></li>
            <li><a href="/my/settings"><?= _("Settings"); ?></a></li>
            <li><a href="/about/rules"><?= _("Rules"); ?></a></li>
            <li><a href="/about/contacts"><?= _("Contacts"); ?></a></li>
        </ul>
    </li>
</ul>