<h1><?= $this->ship->getName(); ?></h1>

<form action="/fleet/build" method="post">
    <input type="hidden" name="planet_id" value="<?= $this->planet->getId(); ?>" />
    <input type="hidden" name="id" value="<?= $this->ship->getId(); ?>" />
    <input type="text" name="count" size="4" maxlength="3"/>
    <input type="submit" name="submit" value="<?= _("build"); ?>"/>
</form>

Cost per unit:<br/>
<?= $this->partial("common/resources.phtml", array( "resources" => $this->ship->getResourceAmounts() ) ); ?>

<p>
    Weapons:
    <ul>
    <?php foreach( $this->ship->getWeapons() as $weapon ) { ?>
        <li><?= $weapon->getType()->getName(); ?>: <?= $weapon->getAmount(); ?> points</li>
    <?php } ?>
    </ul>
</p>

<p>
    Defence:
    <ul>
    <?php foreach( $this->ship->getDefences() as $defence ) { ?>
        <li><?= $defence->getType()->getName(); ?>: <?= $defence->getAmount(); ?> points</li>
    <?php } ?>
    </ul>
</p>