<a href="/fleet/explore"><?= _("Overview"); ?></a> <a href="/fleet/build"><?= _("Build new ships"); ?></a>

<h3><?= _("Ships on"); ?> <strong><?= $this->planet->getName(); ?></strong></h3>
<?php if ( $this->planet->getShips()->count() != 0 ) { ?>
    <form action="/fleet/disband" method="post">
        <ul>
        <?php foreach( $this->planet->getShips() as $ship ) { ?>
            <li>
                <strong><?= $ship->getName(); ?></strong>, <?= $ship->getCount(); ?>
                <input type="text" name="count" value="0" />
            </li>
        <?php } ?>
        </ul>
        <input type="submit" name="submit" value="<?= _("Disband"); ?>"/>
    </form>
<?php } else { ?>
    <strong><?= _("No ships on this planet"); ?></strong>
<?php } ?>