<div>
    <div class="title"><?= $this->user->getLogin(); ?>'s planets</div>
    <?php foreach( $this->user->getSystems() as $system ) { ?>
        <h2>System "<?= $system->getName(); ?>"</h2>
        
        <?php foreach( $system->getPlanets() as $planet ) { ?>
            <a href="/planet/<?= $planet->getId(); ?>"><?= $planet->getName(); ?></a>
            <?= $this->partial("planet/view.phtml", array(
                        "planet" => $planet
                ) ); ?>
        <?php } ?>

        <a href="/ships/<?= $system->getId(); ?>">Fleet</a>
    <?php } ?>
</div>