<?php
$this->user = User_Proxy::getInstance();

$this->headTitle("Site")->setSeparator(" — ");

$this->headMeta()->appendHttpEquiv("Content-Type", "application/xhtml+xml; charset=UTF-8");

$this->headLink()->append((object)array(
    "rel"   => "shortcut icon",
    "href"  => "/favicon.ico",
    "type"  => "image/vnd.microsoft.icon"
));

$this->headLink()
    ->prependStylesheet("/css/basic.css")
    ;

$this->headScript()
    ->prependFile("/libs/mootools/mootools-extend.js")
    ->prependFile("/libs/mootools/mootools-more.js")
    ->prependFile("/libs/mootools/mootools.js")
	->appendFile("/js/AjaxForm.js")
    ;
?>
<?= '<?xml version="1.0" encoding="UTF-8"?>' ?>

<?= $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?= Zend_Registry::get("locale")->getLanguage() ?>">
<head>
    <?= $this->headTitle() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
    <?= $this->headStyle() ?>
    <?= $this->headMeta() ?>
</head>
<body>
	<div class='page'>
		<div class='head'>
			<div class='logo'>
				<a href='/'><h1><?= _("Project xNovae"); ?></h1></a>
			</div>
			<?= $this->partial("common/user_cp.phtml", array( "user" => $this->user ) ); ?>
		</div>
		<div class='body'>
                    <div class="left" style="float: left;">
                        <?php if ( $this->user->isRegistered() ) { ?>
                            <?= $this->partial("common/navigation.phtml"); ?>
                        <?php } ?>
                    </div>
                    <div class="content">
                        <?php if ( $this->user->getCurrentPlanet() ) { ?>
                            <?= $this->partial("common/resources.phtml", array("resources" => $this->user->getCurrentPlanet()->getResourceAmounts() ) ); ?>
                        <?php } ?>
                        <?= $this->layout()->content ?>
                    </div>
		</div>
	</div>
</body>
</html>
