<?php
$id = $this->technology->getId();
$dependencies = $this->technology->getDependencies();

if ( FALSE !== ( $user_technology = $this->planet->getTechnology( $this->technology ) ) ) {
    $this->technology = $user_technology;
}
?>
<tr>
    <td>
        <? //@TODO replace with real statement ?>
        <img src="/img/default_building.gif" />
    </td>
    <td>
    <?php if ( $dependencies->count() != 0 ) { ?>
        <?= _("Depends on"); ?>:<br/>
        <ul>
        <?php foreach( $dependencies as $dependency ) { ?>
            <?php
                $hasDep = $this->planet->hasDependency($dependency);
            ?>
            <li>
                <?php if ( !$hasDep ) { ?>
                    <span class="error">
                <?php } ?>
                    <?= $dependency->getObject()->getName(); ?>, <?= _("Level"); ?> <?= $dependency->getLevel(); ?>
                <?php if ( !$hasDep ) { ?>
                    </span>
                <?php } ?>
            </li>
        <?php } ?>
        </ul>
    </td>
    <?php } ?>
</tr>
<tr>
    <td>
        <strong><?= $this->technology->getName(); ?> ( <?= $this->technology->getLevel(); ?>th level )</strong>
    </td>
    <td>
        <?= $this->technology->getDescription(); ?>

        <?= $this->partial("common/resources.phtml", array( "resources" => $this->building->getResourceAmounts() ) ); ?>
    </td>
</tr>
<tr>
    <td colspan="2">
        <?php if ( $this->building->isReady() && $this->planet->canBuild( $this->building, $this->user ) ) { ?>
            <form action="/new-building/<?= $this->planet->getId(); ?>/<?= $id; ?>" method="post">
                <input type="submit" value="<?= _("Build"); ?> (<?= $this->timePeriod( $this->building->getConstructionTime() ); ?>)"/>
            </form>
        <?php } else if ( !$this->building->isReady() ){ ?>
            <?= _("Construction will be complete in") ?>: <?= $this->timePeriod( $this->building->getRemainingTime() ); ?>
        <?php
        }
        ?>
    </td>
</tr>